# Generated by Django 5.2.6 on 2025-11-10 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('commerces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='commerces.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalogs.restaurant'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerces.order'),
        ),
        migrations.AddField(
            model_name='orderitemoption',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='commerces.orderitem'),
        ),
        migrations.AddField(
            model_name='orderpromo',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerces.order'),
        ),
        migrations.AddField(
            model_name='orderpromo',
            name='promo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerces.promocode'),
        ),
        migrations.AddField(
            model_name='order',
            name='promos',
            field=models.ManyToManyField(blank=True, related_name='orders', through='commerces.OrderPromo', to='commerces.promocode'),
        ),
        migrations.AddConstraint(
            model_name='orderpromo',
            constraint=models.UniqueConstraint(fields=('order', 'promo'), name='unique_order_promo'),
        ),
    ]
